### ISSUE TITLE
Github action fails with versions 12.1811.0 and 12.1812.0

### ISSUE THREAD

**Issue by mpicque** [bridgecrewio/checkov-action#106] opened 2022-10-24 08:24 UTC
Hello,

We encountered an error with versions 12.1811.0 and 12.1812.0 (using tag [v12](https://github.com/bridgecrewio/checkov-action/tree/v12)).

The logs:
```
2022-10-24T08:18:06.4848255Z ##[command]/usr/bin/docker run --name bridgecrewcheckov21282_696948 --label 8d5581 --workdir /github/workspace --rm -e "INPUT_FILE" -e "INPUT_DIRECTORY" -e "INPUT_CHECK" -e "INPUT_SKIP_CHECK" -e "INPUT_COMPACT" -e "INPUT_QUIET" -e "INPUT_API-KEY" -e "INPUT_SOFT_FAIL" -e "INPUT_FRAMEWORK" -e "INPUT_EXTERNAL_CHECKS_DIRS" -e "INPUT_EXTERNAL_CHECKS_REPOS" -e "INPUT_OUTPUT_FORMAT" -e "INPUT_DOWNLOAD_EXTERNAL_MODULES" -e "INPUT_LOG_LEVEL" -e "INPUT_CONFIG_FILE" -e "INPUT_BASELINE" -e "INPUT_SOFT_FAIL_ON" -e "INPUT_HARD_FAIL_ON" -e "INPUT_CONTAINER_USER" -e "INPUT_DOCKER_IMAGE" -e "INPUT_DOCKERFILE_PATH" -e "INPUT_VAR_FILE" -e "INPUT_GITHUB_PAT" -e "INPUT_TFC_TOKEN" -e "INPUT_VCS_BASE_URL" -e "INPUT_VCS_USERNAME" -e "INPUT_VCS_TOKEN" -e "INPUT_BITBUCKET_TOKEN" -e "INPUT_BITBUCKET_APP_PASSWORD" -e "INPUT_BITBUCKET_USERNAME" -e "API_KEY_VARIABLE" -e "GITHUB_PAT" -e "TFC_TOKEN" -e "VCS_USERNAME" -e "VCS_BASE_URL" -e "VCS_TOKEN" -e "BITBUCKET_TOKEN" -e "BITBUCKET_USERNAME" -e "BITBUCKET_APP_PASSWORD" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ds-databricks-workspaces/ds-databricks-workspaces":"/github/workspace" bridgecrew/checkov:2.1.282  "" "." "" "" "" "" "" "" "" "" "sarif" "" "WARNING" "" "" "" "" "" "" "" "--user 0"
2022-10-24T08:18:06.8945528Z BC_FROM_BRANCH=generate_pat_token
2022-10-24T08:18:06.9015252Z BC_TO_BRANCH=main
2022-10-24T08:18:06.9015720Z BC_PR_ID=19
2022-10-24T08:18:06.9016656Z BC_PR_URL=https://github.com/mirakl/ds-databricks-workspaces/pull/19
2022-10-24T08:18:06.9017198Z BC_COMMIT_HASH=3ca9413220585a3419f5f2b9bd3a64fd353ef3b9
2022-10-24T08:18:06.9017882Z BC_COMMIT_URL=https://github.com/mirakl/ds-databricks-workspaces/commit/3ca9413220585a3419f5f2b9bd3a64fd353ef3b9
2022-10-24T08:18:06.9018410Z BC_AUTHOR_NAME=mpicque
2022-10-24T08:18:06.9018860Z BC_AUTHOR_URL=https://github.com/mpicque
2022-10-24T08:18:06.9019232Z BC_RUN_ID=37
2022-10-24T08:18:06.9019781Z BC_RUN_URL=https://github.com/mirakl/ds-databricks-workspaces/actions/runs/3311094408
2022-10-24T08:18:06.9020481Z BC_REPOSITORY_URL=https://github.com/mirakl/ds-databricks-workspaces
2022-10-24T08:18:06.9020948Z running checkov on directory: .
2022-10-24T08:18:06.9021394Z checkov -d .       --output sarif         
2022-10-24T08:18:10.1825912Z 2022-10-24 08:18:10,181 [MainThread  ] [WARNI]  Failed to download module terraform-aws-modules/vpc/aws:3.0.0 (for external modules, the --download-external-modules flag is required)
2022-10-24T08:18:10.1849815Z 2022-10-24 08:18:10,181 [MainThread  ] [WARNI]  Failed to download module git::git@github.com:mirakl/terraform-databricks-workspace.git?ref=v0.5.0:None (for external modules, the --download-external-modules flag is required)
2022-10-24T08:18:10.1851829Z 2022-10-24 08:18:10,181 [MainThread  ] [WARNI]  Failed to download module terraform-aws-modules/vpc/aws:~>3.0 (for external modules, the --download-external-modules flag is required)
2022-10-24T08:18:10.1853683Z 2022-10-24 08:18:10,181 [MainThread  ] [WARNI]  Failed to download module terraform-aws-modules/vpc/aws//modules/vpc-endpoints:~>3.0 (for external modules, the --download-external-modules flag is required)
2022-10-24T08:18:10.1855489Z 2022-10-24 08:18:10,181 [MainThread  ] [WARNI]  Failed to download module git::git@github.com:mirakl/terraform-aws-s3?ref=v0.2.0:None (for external modules, the --download-external-modules flag is required)
2022-10-24T08:18:11.1478870Z ##[error]Unable to process file command 'output' successfully.
2022-10-24T08:18:11.1490838Z ##[error]Invalid format '       _               _              '
```

Our github action file:
```yaml
---
name: Security Scan

on:
  pull_request:
    paths:
      - '.checkov.*'
      - '.github/workflows/security_scan.yml'
      - 'terraform/**'

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
```

The same action works with version 12.1810.0.

**Comment by gruebel** [comment] 2022-10-24 08:48
duplicate of #105

**Closed by gruebel** 2022-10-24 08:48 UTC
