### ISSUE TITLE
Add support for saving the output into a file and upload to github artifactory

### ISSUE THREAD

**Issue by nitishkumar1991** [bridgecrewio/checkov-action#51] opened 2021-08-11 05:02 UTC
Needs the support to save scan results to a file corresponding to output format such as cli to txt, or github_failed_only to txt or junitxml to a xml file and upload to artifactory or repo itself.

**Comment by nmarchini** [comment] 2021-10-20 20:25
I have this use case as well, the output_format option allows us to set JUNIT but there is now way to write the XML to a file so that we an then use another action (such as https://github.com/marketplace/actions/publish-unit-test-results ) to publish the test results in the Workflow summary.

**Comment by toast-gear** [comment] 2022-01-19 11:34
Does it not put the results into `$CHECKOV_RESULTS` which you can then write to disk `echo "$CHECKOV_RESULTS" > results.xml`?

**Comment by mikelax** [comment] 2022-10-03 16:35
Is this a duplicate of #30 ?

**Comment by gruebel** [comment] 2023-03-20 21:10
this is possible via `output_file_path:`

**Closed by gruebel** 2023-03-20 21:10 UTC
